// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// day6func_recursive_cpp
double day6func_recursive_cpp(int init_num, int num_days);
RcppExport SEXP _adventofcode_day6func_recursive_cpp(SEXP init_numSEXP, SEXP num_daysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type init_num(init_numSEXP);
    Rcpp::traits::input_parameter< int >::type num_days(num_daysSEXP);
    rcpp_result_gen = Rcpp::wrap(day6func_recursive_cpp(init_num, num_days));
    return rcpp_result_gen;
END_RCPP
}
// day6func_apply_rec_cpp
double day6func_apply_rec_cpp(arma::vec data6a, int num_days1, int ncore);
RcppExport SEXP _adventofcode_day6func_apply_rec_cpp(SEXP data6aSEXP, SEXP num_days1SEXP, SEXP ncoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type data6a(data6aSEXP);
    Rcpp::traits::input_parameter< int >::type num_days1(num_days1SEXP);
    Rcpp::traits::input_parameter< int >::type ncore(ncoreSEXP);
    rcpp_result_gen = Rcpp::wrap(day6func_apply_rec_cpp(data6a, num_days1, ncore));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adventofcode_day6func_recursive_cpp", (DL_FUNC) &_adventofcode_day6func_recursive_cpp, 2},
    {"_adventofcode_day6func_apply_rec_cpp", (DL_FUNC) &_adventofcode_day6func_apply_rec_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_adventofcode(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
