# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

day6func_recursive_cpp <- function(init_num, num_days) {
    .Call(`_adventofcode_day6func_recursive_cpp`, init_num, num_days)
}

day6func_apply_rec_cpp <- function(data6a, num_days1, ncore) {
    .Call(`_adventofcode_day6func_apply_rec_cpp`, data6a, num_days1, ncore)
}

